/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_madhavanmalolan_ffmpegandroidlibrary_Controller
#define _Included_com_madhavanmalolan_ffmpegandroidlibrary_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madhavanmalolan_ffmpegandroidlibrary_Controller
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madhavanmalolan_ffmpegandroidlibrary_Controller_run
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
